using ApexPerformance.API.Constants;
using ApexPerformance.API.Database;
using ApexPerformance.API.Database.Entities;
using ApexPerformance.API.Services.Interfaces;
using FastEndpoints;
using FastEndpoints.Security;
using FluentValidation;
using Hangfire;
using Microsoft.EntityFrameworkCore;

namespace ApexPerformance.API.Features.Users;

public sealed record RegisterUserRequest(
    string FirstName,
    string LastName,
    string Email,
    string Phone
);

public sealed record RegisterUserResponse(
    Guid Id,
    string Username
);

public sealed class RegisterUserEndpoint : Endpoint<RegisterUserRequest, RegisterUserResponse>
{
    private readonly ApexPerformanceContext _context;
    private readonly IUserService _userService;
    private readonly IEmailService _emailService;
    private readonly IConfiguration _configuration;

    public RegisterUserEndpoint(ApexPerformanceContext context, IUserService userService,
        IEmailService emailService, IConfiguration configuration)
    {
        _context = context;
        _userService = userService;
        _emailService = emailService;
        _configuration = configuration;
    }

    public override void Configure()
    {
        Post("api/users/register");
        AllowAnonymous();
        Options(x => x.WithTags("Users"));
    }

    public override async Task HandleAsync(RegisterUserRequest request, CancellationToken cancellationToken)
    {
        var clientRole = await _context.Roles
            .SingleAsync(x => x.Name == UserRoles.Client, cancellationToken);

        // The visitor doesn't choose a password up front - a random one is
        // generated here and immediately invalidated by the password they
        // set via the emailed link, same as the admin-created-user flow.
        var autoGeneratedPassword = Guid.NewGuid().ToString("N");

        var user = await _userService.CreateUserAccount(request.Email, autoGeneratedPassword, request.Email,
            clientRole, cancellationToken);

        var client = new Client
        {
            FirstName = request.FirstName,
            LastName = request.LastName,
            Email = request.Email,
            Phone = request.Phone,
            User = user
        };

        _context.Clients.Add(client);

        var result = await _context.SaveChangesAsync(cancellationToken);

        if (result == 0)
            ThrowError(ErrorCodes.SavingError);

        // Short-lived, permission-less token (mirrors ForgotPassword) rather
        // than a full login JWT - it's only used to identify the account on
        // the set-password call, not to grant access to the API.
        var token = JwtBearer.CreateToken(
            options: o =>
            {
                o.SigningKey = _configuration["JWTSecretKey"] ?? string.Empty;
                o.ExpireAt = DateTime.Now.AddMinutes(10);
                o.User.Claims.Add(("name", user.UserName), ("sub", user.Id.ToString()));
            });

        BackgroundJob.Enqueue(() => SendWelcomeEmail(user.Id, token));

        await SendAsync(new RegisterUserResponse(user.Id, user.UserName),
            cancellation: cancellationToken);
    }

    public async Task SendWelcomeEmail(Guid userId, string token)
    {
        var user = await _context.Users.SingleAsync(x => x.Id == userId);

        _emailService.SendWelcomeEmail(user, token);
    }
}

public sealed class RegisterUserValidator : Validator<RegisterUserRequest>
{
    public RegisterUserValidator()
    {
        RuleFor(x => x.FirstName).NotEmpty().WithMessage(ErrorCodes.Required);
        RuleFor(x => x.LastName).NotEmpty().WithMessage(ErrorCodes.Required);
        RuleFor(x => x.Email).NotEmpty().WithMessage(ErrorCodes.Required)
            .EmailAddress().WithMessage(ErrorCodes.NotValid);
        RuleFor(x => x.Phone).NotEmpty().WithMessage(ErrorCodes.Required);
    }
}
