using ApexPerformance.API.Constants;
using ApexPerformance.API.Database;
using ApexPerformance.API.Database.Entities;
using ApexPerformance.API.Services.Interfaces;
using FastEndpoints;
using FluentValidation;
using Hangfire;
using Microsoft.EntityFrameworkCore;

namespace ApexPerformance.API.Features.Clients;

public record CreateClientRequest(
    string FirstName,
    string LastName,
    string Email,
    string Phone,
    int Credits,
    List<Guid> Coaches
);

public record CreateClientResponse(
    Guid Id
);

public class CreateClientEndpoint : Endpoint<CreateClientRequest, CreateClientResponse>
{
    private readonly ApexPerformanceContext _context;
    private readonly IUserService _userService;
    private readonly IClientService _clientService;
    private readonly IEmailService _emailService;
    private readonly IAuthenticationService _authenticationService;

    public CreateClientEndpoint(ApexPerformanceContext context, IUserService userService,
        IClientService clientService, IEmailService emailService, IAuthenticationService authenticationService)
    {
        _context = context;
        _userService = userService;
        _clientService = clientService;
        _emailService = emailService;
        _authenticationService = authenticationService;
    }

    public override void Configure()
    {
        Post("api/clients");
        Permissions(UserPermissions.CanCreateClient);
        Options(x => x.WithTags("Clients"));
    }

    public override async Task HandleAsync(CreateClientRequest request, CancellationToken cancellationToken)
    {
        var autoGeneratedPassword = Guid.NewGuid().ToString("N");

        var clientRole = await
            _context.Roles.SingleAsync(x => x.Name == UserRoles.Client, cancellationToken: cancellationToken);

        var user = await _userService.CreateUserAccount(request.Email, autoGeneratedPassword, request.Email,
            clientRole, cancellationToken);

        var newClient = new Client
        {
            FirstName = request.FirstName,
            LastName = request.LastName,
            Email = request.Email,
            Phone = request.Phone,
            Credits = request.Credits,
            User = user
        };

        _context.Clients.Add(newClient);

        var result = await _context.SaveChangesAsync(cancellationToken);

        if (result == 0)
            ThrowError(ErrorCodes.SavingError);

        if (request.Coaches.Count == 0)
        {
            await SendAsync(
                new CreateClientResponse(newClient.Id),
                cancellation: cancellationToken);
            return;
        }

        await _clientService.UpdateClientCoaches(newClient, request.Coaches, cancellationToken);

        var jwtToken = await _authenticationService.GenerateJwtToken(false, user);

        BackgroundJob.Enqueue(() => SendCredentialsEmail(newClient.Id, autoGeneratedPassword, jwtToken));

        await SendAsync(
            new CreateClientResponse(newClient.Id),
            cancellation: cancellationToken);
    }

    public async Task SendCredentialsEmail(Guid clientId, string password, string jwtToken)
    {
        var client = await _context.Clients
            .Include(userType => userType.User)
            .SingleAsync(x => x.Id == clientId);

        _emailService.SendCredentialsEmail(client.User!, password, jwtToken);
    }
}

public sealed class CreateClientValidator : Validator<CreateClientRequest>
{
    public CreateClientValidator()
    {
        RuleFor(x => x.FirstName).NotEmpty().WithMessage(ErrorCodes.Required);
        RuleFor(x => x.LastName).NotEmpty().WithMessage(ErrorCodes.Required);
        RuleFor(x => x.Email).NotEmpty().WithMessage(ErrorCodes.Required);
        RuleFor(x => x.Phone).NotEmpty().WithMessage(ErrorCodes.Required);
    }
}