using ApexPerformance.API.Constants;
using ApexPerformance.API.Database;
using ApexPerformance.API.Database.Entities;
using ApexPerformance.API.Services;
using EFCore.BulkExtensions;
using FastEndpoints;
using FluentValidation;
using MailKit.Net.Smtp;
using Microsoft.EntityFrameworkCore;
using MimeKit;

namespace ApexPerformance.API.Features.Clients;

public record CreateClientRequest(
    string FirstName,
    string LastName,
    string Email,
    string Phone,
    int Credits,
    List<Guid> Coaches
);

public record CreateClientResponse(
    Guid Id,
    string FirstName,
    string LastName,
    string Email,
    string Phone,
    int Credits
);

public class CreateClientEndpoint : Endpoint<CreateClientRequest, CreateClientResponse>
{
    private readonly ApexPerformanceContext _context;
    private readonly IUserService _userService;
    private readonly IConfiguration _configuration;

    public CreateClientEndpoint(ApexPerformanceContext context, IUserService userService,
        IConfiguration configuration)
    {
        _context = context;
        _userService = userService;
        _configuration = configuration;
    }

    public override void Configure()
    {
        Post("api/clients");
        Permissions(nameof(UserPermissions.CanCreateClient));
        Options(x => x.WithTags("Clients"));
    }

    public override async Task HandleAsync(CreateClientRequest request, CancellationToken cancellationToken)
    {
        var autoGeneratedPassword = Guid.NewGuid().ToString("N");

        var user = await _userService.CreateUserAccount(request.Email, autoGeneratedPassword, request.Email,
            cancellationToken);

        var newClient = new Client
        {
            FirstName = request.FirstName,
            LastName = request.LastName,
            Email = request.Email,
            Phone = request.Phone,
            Credits = request.Credits,
            User = user
        };

        _context.Clients.Add(newClient);

        var result = await _context.SaveChangesAsync(cancellationToken);

        if (result == 0)
            ThrowError(ErrorMessages.SavingError);
        
        var coaches = await _context.Coaches
            .Where(x => request.Coaches.Contains(x.Id))
            .ToListAsync(cancellationToken);

        var clientCoaches = coaches
            .Select(coach => new CoachClient
            {
                Client = newClient,
                ClientId = newClient.Id,
                CoachId = coach.Id,
                Coach = coach
            }).ToList();

        await _context.BulkInsertOrUpdateAsync(clientCoaches, cancellationToken: cancellationToken);

        SendEmailWithCredentials(newClient, autoGeneratedPassword);

        await SendAsync(
            new CreateClientResponse(newClient.Id, newClient.FirstName, newClient.LastName, newClient.Email,
                newClient.Phone, newClient.Credits),
            cancellation: cancellationToken);
    }

    private void SendEmailWithCredentials(Client client, string password)
    {
        
    }
}

public sealed class CreateClientValidator : Validator<CreateClientRequest>
{
    public CreateClientValidator()
    {
        RuleFor(x => x.FirstName).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.LastName).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.Email).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.Phone).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.Coaches).NotEmpty().WithMessage(ValidationMessages.Required);
    }
}