using System.Net;
using System.Net.Mail;
using ApexPerformance.API.Constants;
using ApexPerformance.API.Database;
using ApexPerformance.API.Database.Entities;
using ApexPerformance.API.Services;
using FastEndpoints;

namespace ApexPerformance.API.Features.Clients;

public record CreateClientRequest(
    string FirstName,
    string LastName,
    string Email,
    string Phone
);

public record CreateClientResponse(
    Guid Id,
    string FirstName,
    string LastName,
    string Email,
    string Phone
);

public class CreateClientEndpoint : Endpoint<CreateClientRequest, CreateClientResponse>
{
    private readonly ApexPerformanceContext _context;
    private readonly IUserService _userService;
    private readonly IConfiguration _configuration;

    public CreateClientEndpoint(ApexPerformanceContext context, IUserService userService, IConfiguration configuration)
    {
        _context = context;
        _userService = userService;
        _configuration = configuration;
    }

    public override void Configure()
    {
        Post("api/clients");
        Permissions(nameof(UserPermissions.CanCreateClient));
        Options(x => x.WithTags("Clients"));
    }

    public override async Task HandleAsync(CreateClientRequest request, CancellationToken cancellationToken)
    {
        var autoGeneratedPassword = Guid.NewGuid().ToString("N");

        var user = await _userService.CreateUserAccount(request.Email, autoGeneratedPassword, request.Email,
            cancellationToken);

        var newClient = new Client
        {
            FirstName = request.FirstName,
            LastName = request.LastName,
            Email = request.Email,
            Phone = request.Phone,
            User = user
        };

        _context.Clients.Add(newClient);

        var result = await _context.SaveChangesAsync(cancellationToken);

        if (result == 0)
            ThrowError(ErrorMessages.SavingError);

        SendEmailWithCredentials(newClient, autoGeneratedPassword);

        await SendAsync(
            new CreateClientResponse(newClient.Id, newClient.FirstName, newClient.LastName, request.Email,
                request.Phone),
            cancellation: cancellationToken);
    }

    private void SendEmailWithCredentials(Client client, string password)
    {
        Console.WriteLine($"Address: {_configuration.GetSection("MailSettings:Host").Value}");        
        Console.WriteLine($"Port: {int.Parse(_configuration.GetSection("MailSettings:Port").Value!)}");
        Console.WriteLine($"Password: {_configuration.GetSection("MailSettings:Password").Value}");

        try
        {
            var smtpClient = new SmtpClient(_configuration.GetSection("MailSettings:Host").Value,
                int.Parse(_configuration.GetSection("MailSettings:Port").Value!))
            {
                Credentials = new NetworkCredential(_configuration.GetSection("MailSettings:Username").Value,
                    _configuration.GetSection("MailSettings:Password").Value),
                EnableSsl = true
            };

            var mail = new MailMessage
            {
                From = new MailAddress(_configuration.GetSection("MailSettings:Address").Value!),
                Subject = "You Have Been Registered to Apex Performance",
                Body = $"""

                        <!DOCTYPE html>
                        <html lang='en'>
                        <head>
                            <meta charset='UTF-8'>
                            <title>Registration Info</title>
                        </head>
                        <body>
                            <p>Username: {client.Email}</p>
                            <p>Password: {password}</p>
                        </body>
                        </html>
                        """,
                IsBodyHtml = true
            };

            mail.To.Add(client.Email);

            smtpClient.Send(mail);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error sending email: " + ex.Message);
        }
    }
}