using ApexPerformance.API.Constants;
using ApexPerformance.API.Database;
using ApexPerformance.API.Database.Entities;
using ApexPerformance.API.Services;
using EFCore.BulkExtensions;
using FastEndpoints;
using FluentValidation;
using JetBrains.Annotations;
using MailKit.Net.Smtp;
using Microsoft.EntityFrameworkCore;
using MimeKit;

namespace ApexPerformance.API.Features.Coaches;

[UsedImplicitly]
public record CreateCoachRequest(
    string FirstName,
    string LastName,
    string Email,
    string Phone,
    List<Guid> Clients
);

public record CreateCoachResponse(
    Guid Id
);

public class CreateCoachEndpoint : Endpoint<CreateCoachRequest, CreateCoachResponse>
{
    private readonly ApexPerformanceContext _context;
    private readonly IUserService _userService;
    private readonly IEmailService _emailService;
    private readonly ICoachService _coachService;

    public CreateCoachEndpoint(ApexPerformanceContext context, IUserService userService,
        IEmailService emailService, ICoachService coachService)
    {
        _context = context;
        _userService = userService;
        _emailService = emailService;
        _coachService = coachService;
    }

    public override void Configure()
    {
        Post("api/coaches");
        Roles([UserRoles.SuperAdmin, UserRoles.Administrator]);
        Options(x => x.WithTags("Coaches"));
    }

    public override async Task HandleAsync(CreateCoachRequest request, CancellationToken cancellationToken)
    {
        var autoGeneratedPassword = Guid.NewGuid().ToString("N");

        var coachRole = await
            _context.Roles.FirstOrDefaultAsync(x => x.Name == UserRoles.Coach, cancellationToken: cancellationToken);

        if (coachRole is null)
            ThrowError(ErrorMessages.NotFound);

        var user = await _userService.CreateUserAccount(request.Email, autoGeneratedPassword, request.Email, 
            coachRole, cancellationToken);

        var newCoach = new Coach
        {
            FirstName = request.FirstName,
            LastName = request.LastName,
            Email = request.Email,
            Phone = request.Phone,
            User = user
        };

        _context.Coaches.Add(newCoach);

        var result = await _context.SaveChangesAsync(cancellationToken);

        if (result == 0)
            ThrowError(ErrorMessages.SavingError);

        var clients = await _context.Clients
            .Where(x => request.Clients.Contains(x.Id))
            .ToListAsync(cancellationToken: cancellationToken);

        await _coachService.UpdateCoachClients(clients, newCoach, cancellationToken);

        _emailService.SendCredentialsEmail(newCoach.User, autoGeneratedPassword);

        await SendAsync(
            new CreateCoachResponse(newCoach.Id),
            cancellation: cancellationToken);
    }
}

public sealed class CreateCoachValidator : Validator<CreateCoachRequest>
{
    public CreateCoachValidator()
    {
        RuleFor(x => x.FirstName).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.LastName).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.Email).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.Phone).NotEmpty().WithMessage(ValidationMessages.Required);
    }
}