using ApexPerformance.API.Constants;
using ApexPerformance.API.Database;
using ApexPerformance.API.Database.Entities;
using ApexPerformance.API.Services;
using FastEndpoints;
using FluentValidation;
using MailKit.Net.Smtp;
using MimeKit;

namespace ApexPerformance.API.Features.Coaches;

public record CreateCoachRequest(
    string FirstName,
    string LastName,
    string Email,
    string Phone
);

public record CreateCoachResponse(
    Guid Id,
    string FirstName,
    string LastName,
    string Email,
    string Phone
);

public class CreateCoachEndpoint : Endpoint<CreateCoachRequest, CreateCoachResponse>
{
    private readonly ApexPerformanceContext _context;
    private readonly IUserService _userService;
    private readonly IConfiguration _configuration;

    public CreateCoachEndpoint(ApexPerformanceContext context, IUserService userService,
        IConfiguration configuration)
    {
        _context = context;
        _userService = userService;
        _configuration = configuration;
    }

    public override void Configure()
    {
        Post("api/coaches"); 
        Roles([UserRoles.SuperAdmin, UserRoles.Administrator]);
        Options(x => x.WithTags("Coaches"));
    }

    public override async Task HandleAsync(CreateCoachRequest request, CancellationToken cancellationToken)
    {
        var autoGeneratedPassword = Guid.NewGuid().ToString("N");

        var user = await _userService.CreateUserAccount(request.Email, autoGeneratedPassword, request.Email,
            cancellationToken);

        var newCoach = new Coach
        {
            FirstName = request.FirstName,
            LastName = request.LastName,
            Email = request.Email,
            Phone = request.Phone,
            User = user
        };

        _context.Coaches.Add(newCoach);

        var result = await _context.SaveChangesAsync(cancellationToken);

        if (result == 0)
            ThrowError(ErrorMessages.SavingError);

        SendEmailWithCredentials(newCoach, autoGeneratedPassword);

        await SendAsync(
            new CreateCoachResponse(newCoach.Id, newCoach.FirstName, newCoach.LastName, newCoach.Email,
                newCoach.Phone),
            cancellation: cancellationToken);
    }

    private void SendEmailWithCredentials(Coach coach, string password)
    {
        var message = new MimeMessage();
        
        message.From.Add(new MailboxAddress(_configuration["MailConfiguration::FromName"],
            _configuration["MailConfiguration::FromAddress"]));
        
        message.To.Add(new MailboxAddress(coach.FullName, coach.Email));
        
        message.Subject = "You Have Been Registered on Apex Performance";
        
        var templatePath = Path.Combine(Directory.GetCurrentDirectory(), "Templates", "CredentialsEmail.html");
        
        var html = File.ReadAllText(templatePath);

        html = html.Replace("{{ClientFullName}}", coach.FullName);
        
        html = html.Replace("{{Username}}", coach.Email);
        
        html = html.Replace("{{Password}}", password);

        message.Body = new TextPart("html") { Text = html };

        using var smtpClient = new SmtpClient();

        try
        {
            smtpClient.Connect(_configuration["MailConfiguration::Host"],
                int.Parse(_configuration["MailConfiguration::Port"]!),
                MailKit.Security.SecureSocketOptions.StartTls);
            smtpClient.Authenticate(_configuration["MailConfiguration::Username"],
                _configuration["MailConfiguration::Password"]);
            smtpClient.Send(message);
            smtpClient.Disconnect(true);
            Console.WriteLine("Email sent successfully!");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Failed to send email: {ex.Message}");
        }
    }
    
}

public sealed class CreateCoachValidator : Validator<CreateCoachRequest>
{
    public CreateCoachValidator()
    {
        RuleFor(x => x.FirstName).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.LastName).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.Email).NotEmpty().WithMessage(ValidationMessages.Required);
        RuleFor(x => x.Phone).NotEmpty().WithMessage(ValidationMessages.Required);
    }
}